repos:
  - repo: local
    hooks:
      - id: lint
        name: biome lint & format
        entry: pnpm lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: typecheck
        name: typecheck
        entry: pnpm typecheck
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: test
        name: test
        entry: pnpm test
        language: system
        pass_filenames: false
        stages: [pre-push]
